# Generated by Django 5.2.5 on 2025-08-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_option_result'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'questions'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='score',
        ),
    ]
